travis:
  secure:
    BINSTAR_TOKEN: XS3BaU6wUKuX6q5t/FzsLHoGX7mWwuJQLiomFultNTMdT5clVs2j2VTJ+1nRJToK3TiuWzsvM7NK4tLZ+p+vfvLHSTi+dTRzxjVloqI6/a6AAY8bGw3x95OrH/x+S2Xlzqp4bZ/CkJuE4id78lQU1arvZw8yAZT5fyldLGAHDDMF9D1D56rdq9uQyJSL0pKcSnzBGFgE6NFq1dcG8x86lvFVJ1XBBon43kqWwj4O5sNyyiQ/1s9kHPOz17vfB46XXEyp+lGEHGK0L+KXsjkPDmTmys3tp5qt6ZLMIINwZLPjnqSwzqKI/PdyropS3OXMLy32nPpw2y7srhoumCKxGU3aggKhLd9I7X7dbhuwedjbMoraWPTb93LZhSSpqVWzeb6Y/4rabBO3rw8W4qcLdfCwZgRhRayBXf8Crbh27J8viwXxsoheWCk5jdGs9r6mXJTNlQ4nPu0PMN1ujSesvvr78yTjasYhk6P4OWyOg4LIhNVj+WwIdFP09VWwxA6Wnj2wqeAQlJHZN3eE1UIsaJ67MtMwxUvZ1ygzUuD7Lze6rOCk9cNSL0B1FXEOzWnEw0DXUC0SoqgI8ICU3b5AQ1sYqE8i+nLGQ6dGf/lg4Gb8osOk+Npl+Mc2QB6p1LEpMBBoN9xnd98oCXIwCf6c9Sn34Ate9/sf5jXcOEycLx8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
